### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by visualJ** [jonask1337/esp8266-smartdice#1]
![architecture](https://user-images.githubusercontent.com/4355340/35438287-3813466e-0296-11e8-8e17-e20dcda119f8.png)

**Comment by visualJ** [comment]
![hardware](https://user-images.githubusercontent.com/4355340/35439932-5f670730-029d-11e8-83fc-3103393de37c.png)

**Comment by visualJ** [comment]
![hwplan](https://user-images.githubusercontent.com/4355340/35440998-1a349da8-02a2-11e8-85fc-5e9929509fcc.png)

**Comment by jonask1337** [comment]
![image](https://user-images.githubusercontent.com/6740386/36776191-2cb1ec9c-1c65-11e8-9c12-4bda3896d95d.png)

**Comment by jonask1337** [comment]
![img_8417](https://user-images.githubusercontent.com/6740386/36805371-888b8318-1cbd-11e8-9bae-be43948b4cd8.jpg)
